version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    ports:
      - "8080:80"
    volumes:
      - .:/code/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-PHP
    volumes:
      - .:/code/
